http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  cust:
    host: localhost
    paths: '/api/customers(/*)?'
  product:
    host: localhost
    paths: '/api/products(/*)?'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  custsrv:
    url: 'http://localhost:3000/'
  prodsrv:
    url: 'http://localhost:4000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  default-1:
    apiEndpoints:
      - cust
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: custsrv 
              changeOrigin: true
  default-2:
    apiEndpoints:
      - product
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: prodsrv 
              changeOrigin: true
